<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();
        $datos = [
            array( 
                'nombre' =>  "Café Caramel con Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "cafe_01.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Frio con Chocolate Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "cafe_02.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Latte Frio con Chocolate Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 54.9,
                'imagen' => "cafe_03.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Latte Frio con Chocolate Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 54.9,
                'imagen' => "cafe_04.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Malteada Fria con Chocolate Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 54.9,
                'imagen' => "cafe_05.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Mocha Caliente Chico",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "cafe_06.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Mocha Caliente Grande con Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "cafe_07.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Caliente Capuchino Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "cafe_08.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Mocha Caliente Mediano",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "cafe_09.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Mocha Frio con Caramelo Mediano",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "cafe_10.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Mocha Frio con Chocolate Mediano",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "cafe_11.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Espresso",
                'detalles' => $faker->paragraph(),
                'precio' => 29.9,
                'imagen' => "cafe_12.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Capuchino Grande con Caramelo",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "cafe_13.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Café Caramelo Grande",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "cafe_14.jpg",
                'categoria_id' => 1,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 donas de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_01.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 donas Glaseadas",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_02.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona de Fresa",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_03.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona con Galleta de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_04.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona glass con Chispas Sabor Fresa",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_05.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona glass con Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_06.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona de Chocolate con MÁS Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_07.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 donas de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_08.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 donas con Vainilla y Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_09.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 6 Donas",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "donas_10.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 Variadas",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_11.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona Natural con Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_12.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 3 Donas de Chocolate con Chispas",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "donas_13.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dona Chocolate y Coco",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "donas_14.jpg",
                'categoria_id' => 4,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete Galletas de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 29.9,
                'imagen' => "galletas_01.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete Galletas de Chocolate y Avena",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "galletas_02.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de Muffins de Vainilla",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "galletas_03.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete de 4 Galletas de Avena",
                'detalles' => $faker->paragraph(),
                'precio' => 24.9,
                'imagen' => "galletas_04.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Galletas de Mantequilla Variadas",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "galletas_05.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Galletas de sabores frutales",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "galletas_06.jpg",
                'categoria_id' => 6,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa Sencilla",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "hamburguesas_01.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa de Pollo",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "hamburguesas_02.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa de Pollo y Chili",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "hamburguesas_03.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa Queso y Pepinos",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "hamburguesas_04.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa Cuarto de Libra",
                'detalles' => $faker->paragraph(),
                'precio' => 59.9,
                'imagen' => "hamburguesas_05.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hamburguesa Doble Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "hamburguesas_06.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hot Dog Especial",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "hamburguesas_07.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Paquete 2 Hot Dogs",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "hamburguesas_08.jpg",
                'categoria_id' => 2,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "4 Rebanadas de Pay de Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pastel_01.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Waffle Especial",
                'detalles' => $faker->paragraph(),
                'precio' => 49.9,
                'imagen' => "pastel_02.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Croissants De la casa",
                'detalles' => $faker->paragraph(),
                'precio' => 39.9,
                'imagen' => "pastel_03.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pay de Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 19.9,
                'imagen' => "pastel_04.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pastel de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 29.9,
                'imagen' => "pastel_05.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rebanada Pastel de Chocolate",
                'detalles' => $faker->paragraph(),
                'precio' => 29.9,
                'imagen' => "pastel_06.jpg",
                'categoria_id' => 5,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Spicy con Doble Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_01.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Jamón y Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_02.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Doble Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_03.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Especial de la Casa",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_04.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Chorizo",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_05.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Hawaiana",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_06.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Tocino",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_07.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Vegetales y Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_08.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Pepperoni y Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_09.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Aceitunas y Queso",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_10.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Pizza Queso, Jamón y Champiñones",
                'detalles' => $faker->paragraph(),
                'precio' => 69.9,
                'imagen' => "pizzas_11.jpg",
                'categoria_id' => 3,
                'estado' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];
        
        DB::table('productos')->insert($datos);
    }
}
